---

- name: Check if DKIM public key exists on the mail server
  ansible.builtin.stat:
    path: "/etc/opendkim/keys/{{ domain }}/default.txt"
  delegate_to: "{{ mail_ip }}"
  register: dkim_key_file
  when: enable_dkim | bool

- name: Fetch DKIM public key from mail server
  ansible.builtin.slurp:
    src: "/etc/opendkim/keys/{{ domain }}/default.txt"
  delegate_to: "{{ mail_ip }}"
  register: dkim_key_data
  when: 
    - enable_dkim | bool
    - dkim_key_file.stat.exists | default(false)

- name: Write DKIM public key
  blockinfile:
    path: "/etc/bind/zones/db.{{ domain }}"
    marker: "; {mark} ANSIBLE MANAGED BLOCK: DKIM {{ mail_ip }}"
    block: "{{ (dkim_key_data.content | b64decode) | regex_replace(';[^\"]*$', '', multiline=True) }}"
  when: 
    - enable_dkim | bool
    - dkim_key_file.stat.exists | default(false)

